### ISSUE TITLE
releasing/installing extensions

### ISSUE THREAD

**Issue by jeffmcaffer** [cli/go-gh#24]
First, this is awesome. I started out assuming I was going to need to hack my commands into the CLI proper and then found the extension mechanism. Perfect.

I have a question about how to release the extension so others can install it. I wrote up a quick Go-based extension, put it in a gh-* repo and installed it locally (`gh extension install .`). Worked like a charm. So good I want to share. I saw the template put in a release workflow so I went ahead and tagged and pushed and the workflow ran and I duly got a mess of binaries in a release. Great.

I flipped back to my client and ran `gh extension install org/gh-repo` and it complains that `extension is uninstallable: missing executable`. I'm not sure how this is supposed to work. The doc said a few things about having to have "the executable" in the root of the repo but for compiled code
* What's **the** executable for native code where many platforms are supported?
* If we are meant to put all of the various executables at the root of the repo, 
  * what's the naming convention for the executables at the root for all the different platforms?
  * it would be great to have some helpers to generate all those. Even better if we can use Actions and the release workflow.
* Can you pick a Git ref (sha, tag, branch) of the repo that people will get by default? Users randomly getting the latest WIP form the default branch or forcing the dev team's normal development out of the default branch feels troublesome. 
* These files can start to get large. (my trivial one is ~8MB but then times 7 platforms)... and I'll inevitably keep accidentally pushing new versions all the time with my WIP code changes
* What's the role of a release and the workflow in all of this?

Seems ideal here to use the Release mechanism and say that installing gets the executables from latest release by default and you can say something like `install org/repo@v1.4` if you want a specific release.

**Comment by samcoe** [comment]
@jeffmcaffer Can you link to the extension that you are having trouble installing? 

The release workflow in the template is [here](https://github.com/cli/gh-extension-precompile) and it should properly generate binaries and attach them to a release so `gh` can install them. That is the paved paths for binary extensions rather than checking in the precompiled binaries to the repo as the files can be large and lead to huge repo sizes. Having said that the error message you are receiving is `gh` being unable to find the release and binaries so it would seem that something is up there. 

Lastly, right now there is no support for installing a specific version or git ref of an extension, we have an open issue https://github.com/cli/cli/issues/5067 to discuss that feature though.

**Comment by jeffmcaffer** [comment]
Sigh. Seems that I had the name of the org wrong so was trying to install something that didn't exist. Human error. 

Having said that, would be great if the error message pointed out that the repo requested could not be found as that was the more general problem. 

Thanks and sorry for the hassle. Great feature.
